- src/main/java/org/apache/commons/io/FilenameUtils.java
- src/main/java/org/apache/commons/io/IOUtils.java
- src/main/java/org/apache/commons/io/filefilter/AgeFileFilter.java
- src/main/java/org/apache/commons/io/filefilter/SizeFileFilter.java
> Control flow style

- src/main/java/org/apache/commons/io/FileUtils.java
Applying patch found here: https://issues.apache.org/jira/browse/IO-629
> IO-629: Providing more meaningful exceptions on file delete

- src/main/java/org/apache/commons/io/comparator/SizeFileComparator.java
- src/main/java/org/apache/commons/io/file/PathUtils.java
- src/main/java/org/apache/commons/io/filefilter/FileFilterUtils.java
- src/main/java/org/apache/commons/io/input/BOMInputStream.java
1. Redundant assignment of local variables removed
2. Lambda expression simplified
> Make some simplifications

- src/main/java/org/apache/commons/io/FileUtils.java
- src/main/java/org/apache/commons/io/comparator/SizeFileComparator.java
- src/main/java/org/apache/commons/io/file/spi/FileSystemProviders.java
- src/main/java/org/apache/commons/io/filefilter/AgeFileFilter.java
- src/main/java/org/apache/commons/io/output/AbstractByteArrayOutputStream.java
- src/test/java/org/apache/commons/io/DirectoryWalkerTestCase.java
- src/test/java/org/apache/commons/io/FileUtilsCleanDirectoryTestCase.java
- src/test/java/org/apache/commons/io/FileUtilsCleanSymlinksTestCase.java
- src/test/java/org/apache/commons/io/FileUtilsTestCase.java
- src/test/java/org/apache/commons/io/IOUtilsTestCase.java
- src/test/java/org/apache/commons/io/LineIteratorTestCase.java
- src/test/java/org/apache/commons/io/file/DirectoryStreamFilterTest.java
- src/test/java/org/apache/commons/io/input/SwappedDataInputStreamTest.java
- src/test/java/org/apache/commons/io/input/XmlStreamReaderTest.java
- src/test/java/org/apache/commons/io/input/XmlStreamReaderUtilitiesTest.java
- src/test/java/org/apache/commons/io/input/buffer/CircularBufferInputStreamTest.java
- src/test/java/org/apache/commons/io/input/compatibility/XmlStreamReader.java
- src/test/java/org/apache/commons/io/output/FileWriterWithEncodingTest.java
Minor improvement:
* Add Final
* Unused import
* Unnecessary semicolon
> Minor improvements

- src/main/java/org/apache/commons/io/FileUtils.java
- src/test/java/org/apache/commons/io/FileUtilsTestCase.java
- added test cases
- updated javadoc for "copy and delete" with setLastModified
> IO-700: provide method overload for moveFile

- src/main/java/org/apache/commons/io/FileCleaningTracker.java
- src/main/java/org/apache/commons/io/FileUtils.java
- src/main/java/org/apache/commons/io/LineIterator.java
- src/main/java/org/apache/commons/io/file/DeletingPathVisitor.java
- src/main/java/org/apache/commons/io/file/PathUtils.java
- src/main/java/org/apache/commons/io/input/BoundedInputStream.java
- src/main/java/org/apache/commons/io/input/BoundedReader.java
- src/main/java/org/apache/commons/io/input/BufferedFileChannelInputStream.java
- src/main/java/org/apache/commons/io/input/UnixLineEndingInputStream.java
- src/main/java/org/apache/commons/io/input/WindowsLineEndingInputStream.java
- src/main/java/org/apache/commons/io/monitor/FileAlterationMonitor.java
- src/main/java/org/apache/commons/io/output/CountingOutputStream.java
- src/main/java/org/apache/commons/io/output/DeferredFileOutputStream.java
- src/main/java/org/apache/commons/io/output/QueueOutputStream.java
- src/test/java/org/apache/commons/io/IOUtilsTestCase.java
- src/test/java/org/apache/commons/io/input/ObservableInputStreamTest.java
- src/test/java/org/apache/commons/io/input/TailerTest.java
- src/test/java/org/apache/commons/io/input/compatibility/XmlStreamReader.java
* Add final
* Remove redundant initializer
* simplify conditions
> Minor Improvement:

- src/main/java/org/apache/commons/io/input/BufferedFileChannelInputStream.java
usage of DirectBuffer will cause IllegalAccessError.
This pr aims to fix it.
https://issues.apache.org/jira/browse/IO-720
> [IO-720] Fix error about usage of DirectBuffer in JRE 16/17

- src/main/java/org/apache/commons/io/monitor/FileAlterationMonitor.java
- src/test/java/org/apache/commons/io/monitor/FileAlterationMonitorTestCase.java
Added a simple wrapper constructor accepting a collection.
> Add constructor accepting collection of file alteration observers

- src/test/java/org/apache/commons/io/ByteOrderMarkTestCase.java
- src/test/java/org/apache/commons/io/CopyUtilsTest.java
- src/test/java/org/apache/commons/io/FileCleaningTrackerTestCase.java
- src/test/java/org/apache/commons/io/FileUtilsTestCase.java
- src/test/java/org/apache/commons/io/FilenameUtilsTestCase.java
- src/test/java/org/apache/commons/io/IOIndexedExceptionTestCase.java
- src/test/java/org/apache/commons/io/IOUtilsCopyTestCase.java
- src/test/java/org/apache/commons/io/IOUtilsTestCase.java
- src/test/java/org/apache/commons/io/IOUtilsWriteTestCase.java
- src/test/java/org/apache/commons/io/LineIteratorTestCase.java
- src/test/java/org/apache/commons/io/comparator/ExtensionFileComparatorTest.java
- src/test/java/org/apache/commons/io/comparator/NameFileComparatorTest.java
- src/test/java/org/apache/commons/io/comparator/PathFileComparatorTest.java
- src/test/java/org/apache/commons/io/filefilter/ConditionalFileFilterAbstractTestCase.java
- src/test/java/org/apache/commons/io/filefilter/FileFilterTestCase.java
- src/test/java/org/apache/commons/io/input/CharSequenceInputStreamTest.java
- src/test/java/org/apache/commons/io/input/ObservableInputStreamTest.java
- src/test/java/org/apache/commons/io/input/RandomAccessFileInputStreamTest.java
- src/test/java/org/apache/commons/io/input/SwappedDataInputStreamTest.java
- src/test/java/org/apache/commons/io/output/DeferredFileOutputStreamTest.java
- src/test/java/org/apache/commons/io/output/XmlStreamWriterTest.java
- src/test/java/org/apache/commons/io/test/TestUtils.java
Change assertions with simpler but equivalent calls.
> Simplify Assertions in tests

- pom.xml
Make the sun.* references from BufferedFileChannelInputStream optional
> IO-734 The OSGi manifest now contains sun.* import packages

- src/main/java/org/apache/commons/io/CopyUtils.java
- src/main/java/org/apache/commons/io/FileSystemUtils.java
- src/main/java/org/apache/commons/io/FileUtils.java
- src/main/java/org/apache/commons/io/FilenameUtils.java
- src/main/java/org/apache/commons/io/file/PathUtils.java
- src/main/java/org/apache/commons/io/function/IOConsumer.java
- src/main/java/org/apache/commons/io/input/BufferedFileChannelInputStream.java
- src/main/java/org/apache/commons/io/output/ThresholdingOutputStream.java
- src/test/java/org/apache/commons/io/ByteOrderMarkTestCase.java
- src/test/java/org/apache/commons/io/FileUtilsTestCase.java
* Remove Unnecessary interface modifier
* Make final var
* Simplify conditions
* Simplify assertions
> Minor changes

- src/test/java/org/apache/commons/io/filefilter/AndFileFilterTestCase.java
First contribution, added a test case to improve the coverage of `AndFileFilter`. Currently learning the codebase to start contributing!
> Add test to make sure the setter of AndFileFilter works correctly

- src/main/java/org/apache/commons/io/IOUtils.java
- src/test/java/org/apache/commons/io/FilenameUtilsTestCase.java
- src/test/java/org/apache/commons/io/IOUtilsCopyTestCase.java
- src/test/java/org/apache/commons/io/IOUtilsTestCase.java
- src/test/java/org/apache/commons/io/filefilter/FileFilterTestCase.java
- src/test/java/org/apache/commons/io/input/CharacterSetFilterReaderTest.java
- src/test/java/org/apache/commons/io/input/TailerTest.java
- src/test/java/org/apache/commons/io/input/TeeInputStreamTest.java
https://issues.apache.org/jira/browse/IO-746
> IO-746: Drop unnecessary casts and conversions

- src/main/java/org/apache/commons/io/file/PathUtils.java
- src/test/java/org/apache/commons/io/file/PathUtilsTest.java
Add PathUtils.readAttributes(Path, Class<A>, LinkOption...).
> Add PathUtils.isPosix(Path, LinkOption...).

- src/main/java/org/apache/commons/io/output/AbstractByteArrayOutputStream.java
fix typos in src/main/java/org/apache/commons/io/output/AbstractByteArrayOutputStream.java
> (doc) fix typos in AbstractByteArrayOutputStream.java

- src/main/java/org/apache/commons/io/input/ReaderInputStream.java
Resolves:
- https://issues.apache.org/jira/browse/IO-713
- https://issues.apache.org/jira/browse/IO-715
Please let me know if you want anything changed, or if I should split this pull request.
> Improve `ReaderInputStream` documentation

- src/main/java/org/apache/commons/io/filefilter/SymbolicLinkFileFilter.java
- src/test/java/org/apache/commons/io/filefilter/SymbolicLinkFileFilterTest.java
This should be pulled after IO-789
> IO-790 symbolic link file filter test incomplete, needs to handle windows issues

- src/test/java/org/apache/commons/io/FileUtilsCleanDirectoryTest.java
- src/test/java/org/apache/commons/io/FileUtilsDeleteDirectoryLinuxTest.java
- src/test/java/org/apache/commons/io/FilenameUtilsTest.java
- src/test/java/org/apache/commons/io/input/NullInputStreamTest.java
- src/test/java/org/apache/commons/io/input/NullReaderTest.java
- src/test/java/org/apache/commons/io/input/TaggedInputStreamTest.java
- src/test/java/org/apache/commons/io/input/TaggedReaderTest.java
- src/test/java/org/apache/commons/io/input/TeeInputStreamTest.java
- src/test/java/org/apache/commons/io/input/TeeReaderTest.java
- src/test/java/org/apache/commons/io/input/XmlStreamReaderTest.java
- src/test/java/org/apache/commons/io/output/TeeOutputStreamTest.java
- src/test/java/org/apache/commons/io/output/TeeWriterTest.java
- src/test/java/org/apache/commons/io/output/UncheckedAppendableTest.java
- Replace `try/catch` with JUnit5 `assertThrows`
FYI
@garydgregory @kinow
> Use assertThrows

- src/test/java/org/apache/commons/io/FileUtilsTest.java
- src/test/java/org/apache/commons/io/input/AbstractInputStreamTest.java
- src/test/java/org/apache/commons/io/input/TeeReaderTest.java
> remove some unused variables Eclipse warned about

- src/main/java/org/apache/commons/io/filefilter/IOFileFilter.java
> Add PathMatcher to IOFileFilter class Javadoc

- src/main/java/org/apache/commons/io/build/AbstractOrigin.java
now that IO-795 is fixed @garydgregory
> [IO-795] Finish TODO on CharSequenceInputStream

- src/main/java/org/apache/commons/io/input/ThrottledInputStream.java
and small Javadoc improvements
@garydgregory
> limit public API to enhance evolvability in future

- src/test/java/org/apache/commons/io/FileUtilsTest.java
> Reduce noise in FileUtilsTest

- src/main/java/org/apache/commons/io/FileUtils.java
- src/test/java/org/apache/commons/io/FileUtilsTest.java
> Uncomment and update null tests for FileUtils.toURLs(File...)

- src/main/java/org/apache/commons/io/input/ChecksumInputStream.java
- src/test/java/org/apache/commons/io/input/ChecksumInputStreamTest.java
Should replace the Apache Commons Compress version.
@elharo
> Add ChecksumInputStream and test

- src/main/java/org/apache/commons/io/FilenameUtils.java
@garydgregory I read through the entire class to to figure out its intent and I think the edits here —which are purely to doc comments, not to code — somewhat help to explain that.
Having said that, this class has some issues, including using a lot of non-standard terminology and probably some bugs on edge conditions. This will require additional PRs for code and tests.
> [IO-836] Update FileNameUtils Javadoc

- src/test/java/org/apache/commons/io/input/NullInputStreamTest.java
copy pasta errors @garydgregory
> repair bad asserts

- src/main/java/org/apache/commons/io/FileUtils.java
- src/test/java/org/apache/commons/io/FileUtilsTest.java
No API changes. No existing tests failed. I added a new test for this. @garydgregory
> [IO-808] non writeable destinations are I/O errors

- src/main/java/org/apache/commons/io/output/ThresholdingOutputStream.java
- src/test/java/org/apache/commons/io/output/ThresholdingOutputStreamTest.java
> [IO-405] handle zero and negative thresholds

- src/site/xdoc/index.xml
> [IO-832] fix package links
